# Generated by Django 3.2.25 on 2025-01-11 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_slug',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
